### PR TITLE
Merge various improvements from my branch

### PR DESCRIPTION
**Pull request by jwakely**
This includes some improvements from @briansorahan's branch (fix code warnings, add dockerfile, Travis CI support) and some of my own (Makefile improvements, tests, code cleanup).

### CODE REVIEW

**Comment by jwakely** [comment]
Hi, this includes the improvements I mentioned in #4 back in February last year. I don't seem to be able to push directly to your repo, so created this pull request instead. Let me know if you'd like any changes, or prefer it to be split up into several pull requests.

**Comment by jwakely** [comment]
Or if you don't want to merge it at all, that's fine too :-)

I was reminded of this repo by seeing https://www.youtube.com/watch?v=bol5tebaQMU today which makes use of your code for uploading to the Analog RYTM.

**Comment by bsl** [comment]
Hi, Jonathan. Thank you. Would you like to be a collaborator on this repo?

**Comment by jwakely** [comment]
Hi Brian, yes, that would be great -- I thought I already was, based on the discussion in #4, but don't seem to be able to push to it.

If you're happy to trust me with access to the repo I'd be very happy to make these changes directly and not bother you with them :smile:

**Comment by bsl** [comment]
Oh, it's odd -- GitHub tells me it's still awaiting your response (from a long time ago). I'll see if I can cancel it and add you again.

**Comment by jwakely** [comment]
Yeah, looks like I just missed the invite and never accepted it - sorry!

**Comment by bsl** [comment]
Thanks very much for working on this stuff.

**Pull request merged**
